spring:
  ai:
    openai:
      api-key: sk-wotoyetgihgqwaqodvjgmutyvkymfpnlbolyjjbzletkuold
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B  #对话模型
#          model: Kwai-Kolors/Kolors  #图像生成模型
#          model: FunAudioLLM/SenseVoiceSmall #语音模型
          temperature: 0.7
          max-tokens: 2048
          top-p: 1.0
          frequency-penalty: 0.0
          presence-penalty: 0.0