spring:
  application:
    name: spring-ai-mcp-client-demo
  profiles:
    active: siliconflow
  ai:
    mcp:
      client:
        name: spring-ai-mcp-client
        version: 1.0.0
        type: SYNC
        request-timeout: 20s
        sse:
          connections:
            server1:
              url: http://localhost:8081
        toolcallback:
          enabled: true