spring:
  ai:
    openai:
      api-key: sk-056Wy3rHmMo0sC10NNXJDQ
      base-url: https://ai.ludp.lenovo.com/ics-nm/projects/123/salespitch-ds/aiverse/endpoint
      chat:
        options:
          model: DeepSeek-R1-Distill-Qwen-32B
          temperature: 0.7
          max-tokens: 2048
          top-p: 1.0
          frequency-penalty: 0.0
          presence-penalty: 0.0