spring:
  application:
    name: spring-ai-ollama-demo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
        options:
          temperature: 0.7

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.retry: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.client.DefaultRestClient: DEBUG